### ISSUE TITLE
Game crashes when hovering over ingredients in mixer recipies

### ISSUE THREAD

**Issue by snerl1** [TheStaticVoid/StaTech-Industry#479] opened 2024-03-21 14:30 UTC
The game crashes when I hover over the ingredients for mechanical mixer recipes in the REI menu. This specific crash was in multiplayer but it was happening in singeplayer as well.

Here is a crash report from said issue.
[crash-2024-03-21_09.24.59-client.txt](https://github.com/TheStaticVoid/StaTech-Industry/files/14696584/crash-2024-03-21_09.24.59-client.txt)

**Comment by TheStaticVoid** [comment] 2024-03-21 14:51
Duplicate of #477 

Still awaiting fixed version release from Create

**Closed by TheStaticVoid** 2024-03-21 14:51 UTC
