### ISSUE TITLE
Crafting Tweaks dupe bug

### ISSUE THREAD

**Issue by memester420** [TheStaticVoid/StaTech-Industry#307] opened 2023-07-28 21:37 UTC
The compress items keybind lets you create a full dust out of just one tiny dust. This is on the latest version of the pack.

**Comment by TheStaticVoid** [comment] 2023-07-28 21:38
Hm they said they fixed this wtf

**Comment by TheStaticVoid** [comment] 2023-07-28 22:11
Cannot reproduce, could you provide some more info?

**Comment by memester420** [comment] 2023-07-28 22:22
Oh yeah sorry.  I just mashed k on a stack of tiny brick dust with the crafting table open and it turned the last into a full dust with only 1 left in the stack. I tried it again with splitting the stack into several stacks of one and it turned each into a full stack.

**Comment by TheStaticVoid** [comment] 2023-07-28 22:37
Yep this is confirmed. It looks like there was an issue about this on the CraftingTweaks github but they closed it without any changes so I'm not sure what's going on there as of now.

I really don't want to have to remove this mod again, but this is pretty game breaking.

**Closed** 2023-07-29 01:56 UTC
Labels: bug
