### ISSUE TITLE
Tooltip Crash for Tin Dust in bronze dust mixer recipe

### ISSUE THREAD

**Issue by Tornado642048** [TheStaticVoid/StaTech-Industry#482] opened 2024-03-26 22:53 UTC
[Crash Stacktrace.txt](https://github.com/TheStaticVoid/StaTech-Industry/files/14765364/Crash.Stacktrace.txt)

Modpack version: 1.1.12 (prism launcher 6.3)
While viewing the recipe for Bronze dust in the mixer, when hovering over the tin dus, the game crashed.

Order of operations leading up to the crash (may or may not be important):
1. Open the quest book
2. Open the first chapter
3. click on the bronze quest
4. click on the bronze ingot item(to view recipe)
5. go to a tab for smelting bronze dust
6. get recipe for bronze dust by pressing 'R' while hovering over item:bronze dust
7. go to tab for mixer recipe
8. (or not)hover over [any item]
9. hover over tin dust -> crash

**Comment by TheStaticVoid** [comment] 2024-03-27 00:07
Duplicate of https://github.com/TheStaticVoid/StaTech-Industry/issues/477

Still awaiting fixed version release from Create

**Closed by TheStaticVoid** 2024-03-27 00:07 UTC
Labels: duplicate
