### ISSUE TITLE
Crush when i put mouse over the recipe with mixer

### ISSUE THREAD

**Issue by CribaGIT** [TheStaticVoid/StaTech-Industry#481] opened 2024-03-25 14:45 UTC
When I put the mouse over the recipe with the mixer it crushes the pack the crafting is tin and I copepr to make bronze or any other crafting with the mixer of the create

**Comment by TheStaticVoid** [comment] 2024-03-25 15:52
Duplicate of #477

Still awaiting fixed version release from Create

**Closed by TheStaticVoid** 2024-03-25 15:52 UTC
Labels: duplicate
